export const PRODUCT_BYID_REQUEST = 'PRODUCT_BYID_REQUEST'
export const PRODUCT_BYID_SUCCESS = 'PRODUCT_BYID_SUCCESS'
export const PRODUCT_BYID_FAIL = 'PRODUCT_BYID_FAIL'

export const PRODUCT_ALL_REQUEST = 'PRODUCT_ALL_REQUEST'
export const PRODUCT_ALL_SUCCESS = 'PRODUCT_ALL_SUCCESS'
export const PRODUCT_ALL_FAIL = 'PRODUCT_ALL_FAIL'

